# Generated by Django 6.1.1 on 2026-09-22 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_reports/%Y/%m/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('predicted_class', models.CharField(blank=True, max_length=150)),
                ('crop_detected', models.CharField(blank=True, max_length=100)),
                ('disease_detected', models.CharField(blank=True, max_length=150)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('classifier_mode', models.CharField(blank=True, help_text="'cnn' or 'demo_heuristic'", max_length=20)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_band', models.CharField(blank=True, max_length=10)),
                ('advisory_text', models.TextField(blank=True)),
                ('advisory_language', models.CharField(default='en', max_length=8)),
                ('advisory_sources', models.JSONField(blank=True, default=list)),
                ('advisory_mode', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending processing'), ('advisory_sent', 'Advisory sent (auto)'), ('flagged', 'Flagged for expert review'), ('confirmed', 'Expert confirmed'), ('corrected', 'Expert corrected'), ('referred_lab', 'Referred to lab')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_reports', to='farms.cropcycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reports', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('confirm', 'Confirmed AI diagnosis'), ('correct', 'Corrected diagnosis'), ('reject', 'Rejected (not a valid case)')], max_length=10)),
                ('corrected_label', models.CharField(blank=True, help_text='Set only if action=correct', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('disease_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reports.diseasereport')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='PestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(help_text='e.g. Fall armyworm', max_length=150)),
                ('trap_count', models.PositiveIntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_reports', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('temperature_c', models.FloatField()),
                ('humidity_pct', models.FloatField()),
                ('rainfall_mm_7d', models.FloatField(help_text='Rainfall over the last 7 days, mm')),
                ('wind_kmh', models.FloatField()),
                ('source', models.CharField(default='synthetic', help_text="'openweathermap' or 'synthetic'", max_length=30)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='farms.farm')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='weather_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.weathersnapshot'),
        ),
    ]
