# Generated by Django 5.2.17 on 2026-09-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasereport',
            name='advisory_audio',
            field=models.FileField(blank=True, null=True, upload_to='advisory_audio/%Y/%m/'),
        ),
    ]
