# Generated by Django 6.1.1 on 2026-09-22 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('expert', 'Expert / Lab'), ('officer', 'Agriculture Officer')], default='farmer', max_length=16)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('mr', 'Marathi'), ('hi', 'Hindi')], default='en', max_length=8)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('taluka', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
